[package]
name = "boon-procmacro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
boon = {path="../lib"}
syn = {version="2.0.10", features=["full", "extra-traits"]}
quote = "1.0.26"
