[package]
name = "boongen"
version = "0.1.0"
edition = "2021"

[dependencies]
boon = { path = "../lib", features = ["internal"] }
boon-procmacro = { path = "../macro" }

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
